src/tweets_demo/models/tweet.py
from sqlalchemy import Column, Integer, String, ForeignKey, Index
from sqlalchemy.orm import relationship, validates
from tweets_demo.app import db
import re
from datetime import datetime
import ipdb


class Tweet(db.Model):
    from tweets_demo.models.comment import Comment

    __tablename__ = "tweets"
    id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
    id_user = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_at = Column(String(255), nullable=False)
    content = Column(String(256), nullable=False)
    comments = relationship("Comment", primaryjoin="Tweet.id==Comment.id_tweet")

    def __init__(self, id_user="", created_at="", content=""):
        self.id_user = id_user
        self.created_at = created_at
        self.content = content

    def __repr__(self):
        return f"id:{self.id}, id_user: {self.id_user}, created_at: {self.created_at}, content:{self.content}"

    # def _is_valid_id_user(self, id_user):
    #     regex = "^[0-9][0-9]*$"
    #     if not re.match(regex, id_user):
    #         raise ValueError("User id is not correct")
    #     return id_user

    # def _is_valid_date_time(self, created_at):
    #     if not datetime.strptime(created_at, "%d-%m-%Y %H:%M"):
    #         raise ValueError("Not a valid datetime")
    #     # ipdb.set_trace()
    #     return created_at

    @validates(
        "content",
    )
    def validates_fields(self, key, value):
        if not getattr(self, "errors", None):
            self.errors = []

        if not value:
            self.errors.append(f"{key} is missing")

        if key == "content":
            if len(value) < 1:
                self.errors.append(f"{key} should have at least 1 character")
            if len(value) < 1:
                self.errors.append("Content cannot excede 256 characters.")

        return value

    def is_valid(self):
        return len(self.errors) == 0

src/tweets_demo/controllers/comments.py
from flask import Flask, Blueprint, session, jsonify, render_template, url_for, request, redirect, flash
import ipdb
from sqlalchemy import delete


from datetime import datetime

comments_blueprint = Blueprint("comments", __name__)

from tweets_demo.app import db
from tweets_demo.controllers.application import current_user, current_date, login_required
from tweets_demo.models.user import User
from tweets_demo.models.comment import Comment


@comments_blueprint.route("/comments/<id>")
@login_required
def show(current_user, id):

    comment_query = (
        Comment.query.join(User, User.id == Comment.id_user)
        .filter(Comment.id == id)
        .add_columns(User.name, User.username, Comment.content, Comment.id)
        .all()
    )
    comment = comment_query[0]
    author = session["logged_in"]["user_id"]
    return render_template("comments/show.html", comment=comment)


@comments_blueprint.route("/comments/new/<id>")
@login_required
def new(current_user, id):
    return render_template("/comments/new.html")


@comments_blueprint.route("/comments/new/", methods=["POST"])
@login_required
def create(current_user):
    tweet_id = request.form.get("tweet_id")

    comment = Comment(
        id_user=session["logged_in"]["user_id"],
        id_tweet=tweet_id,
        created_at=current_date(),
        content=request.form.get("content"),
    )
    if comment.is_valid():
        flash("Comment added")
        db.session.add(comment)
        db.session.commit()
        return redirect("/feed")
    else:
        return render_template("/comments/new.html", errors=errors)


@comments_blueprint.route("/comments/<id>/delete", methods=["POST"])
@login_required
def destroy(current_user, id):

    comment = Comment.query.filter(Comment.id == id).first()

    flash("Comment removed")
    db.session.delete(comment)
    db.session.commit()
    return redirect("/feed")

src/tweets_demo/controllers/tweets.py
from flask import Flask, Blueprint, session, jsonify, render_template, url_for, request, redirect, flash
import ipdb


tweets_blueprint = Blueprint("tweets", __name__)

from tweets_demo.app import db
from tweets_demo.controllers.application import current_date, login_required, my_render_template
from tweets_demo.models.tweet import Tweet
from tweets_demo.models.user import User
from tweets_demo.models.comment import Comment


@tweets_blueprint.route("/feed")
@login_required
def index(current_user):
    return my_render_template("tweets/index.html", tweets=current_user.tweets, user=current_user)


@tweets_blueprint.route("/tweets/<id>")
@login_required
def show(current_user, id):
    tweet_query = (
        Tweet.query.join(User, User.id == Tweet.id_user)
        .filter(Tweet.id == id)
        .add_columns(User.name, User.username, Tweet.content, Tweet.id, Tweet.id_user)
        .all()
    )
    tweet = tweet_query[0]

    all_comments = (
        User.query.join(Comment, Comment.id_user == User.id)
        .filter(Comment.id_tweet == id)
        .add_columns(Comment.content, Comment.id, Comment.id_user, User.name, User.username)
        .all()
    )
    logedin_user_id = session["logged_in"]["user_id"]
    mess = ""
    if len(all_comments) == 0:
        mess = "No comments to this tweet"
    return my_render_template(
        "tweets/show.html",
        tweet=tweet,
        all_comments=all_comments,
        mess=mess,
        logedin_user_id=logedin_user_id,
    )


@tweets_blueprint.route("/tweets/new")
@login_required
def new(current_user):
    return my_render_template("/tweets/new.html")


@tweets_blueprint.route("/tweets/new", methods=["POST"])
@login_required
def create(current_user):
    tweet = Tweet(
        id_user=session["logged_in"]["user_id"],
        created_at=current_date(),
        content=request.form.get("content"),
    )
    if tweet.is_valid:
        flash("Tweet added")
        db.session.add(tweet)
        db.session.commit()
        return redirect("/")
    else:
        return my_render_template("/tweets/new.html", errors=errors)


@tweets_blueprint.route("/tweets/<id>/delete", methods=["POST"])
@login_required
def destroy(current_user, id):
    tweet = Tweet.query.filter(Tweet.id == id).first()
    comments = Comment.query.filter(Comment.id_tweet == id).all()

    flash("Tweet and comments removed")
    for comment in comments:
        db.session.delete(comment)
        # db.session.commit()

    db.session.delete(tweet)
    db.session.commit()
    return redirect("/feed")

src/tweets_demo/templates/tweets/index.html
{% extends "index.html" %}
{% block content%}

{{render_partial('tweets/list.html', user = user, tweets = tweets)}}

{%endblock%}

src/tweets_demo/templates/tweets/list.html
{% block tweets_list %}
<div class="tweets">     
    {% for tweet in tweets%}
    <div class="tweet">
        <h3><div id="tweet">{{user.name}} tweeted: {{tweet.content}}</div></h3>
        <h4> Comments:<h4>
        {% for comment in tweet.comments %}
            {{comment.user.username}} : <br>{{comment.content}}
                {% if user.id == comment.id_user%}
            <form action="{{url_for('comments.destroy', id = comment.id)}}" method="POST">
               <input type="submit" value="Delete comment">
            </form>
                {% endif %}
            <hr>
        {% endfor %}
        <form method="post" action="/comments/new">
            <input type="hidden" name="tweet_id" value="{{tweet.id}}">
            <input type="text" name="content" placeholder="add a comment"></input>
            <button type="submit">Submit</button>
        </form>
    </div>
    {% endfor %}
</div>
{% endblock %}

src/tweets_demo/templates/tweets/mytweet.html
{% extends 'index.html' %}
{% block title %}View my tweets{% endblock %} 
{% block content%}
<div class="tweets">     
                {% for tweet in tweets%}
                <div class="tweet">
                    <div id="tweet">{{tweet.name}}({{tweet.username}}):</div>
                    <p>
                        <a href="{{ url_for('tweets.show', id= tweet.id) }}">{{tweet.content}}</a>
                    </p>
                </div>
                {% endfor %}
            </div>
{% endblock %}

src/tweets_demo/templates/tweets/new.html
{% extends 'index.html' %}
{% block title %}Create new tweet{% endblock %} 
{% block content%}
<p>Add a new tweet</p>
    <form method="post" url='/tweet/new'>
        <input type="text" name="content" placeholder="Write your ideas"></input>
        <button type="submit">Submit</button>
    </form>

    {% if errors %}
        {{ errors }}
    {% endif %}
{% endblock %}

src/tweets_demo/templates/tweets/show.html
{% extends 'index.html' %}
{% block title %}View tweet{% endblock %} 
{% block content%}
<hr>
<p>{{tweet.name}} ({{tweet.username}})</p>
<p>{{ tweet.content }}</p>
<hr>
{% for comment in all_comments %}
    <a href="{{ url_for('comments.show', id= comment.id) }}">{{comment.name}} ({{comment.username}}) wrote {{comment.content}}</a>
    {% if logedin_user_id == comment.id_user%}
        <form action="{{url_for('comments.destroy', id = comment.id)}}" method="POST">
            <input type="submit" value="Delete comment">
        </form>
    {% endif %}
    <hr>
{% endfor %}
{% if mess %}
    {{ mess }}
{% endif %}
<div><a href="{{ url_for('comments.new', id= tweet.id) }}">Add a comment</a></div>
{% if logedin_user_id == tweet.id_user%}
    <form action="{{url_for('tweets.destroy', id = tweet.id)}}" method="POST">
        <input type="submit" value="Delete tweet">
    </form>
{% endif %}
{% with messages = get_flashed_messages() %}
    <div class=flashes>
    {% if messages %}
        <ul>
        {% for message in messages %}<li>
            <span style=“color:orange”>{{ message }}</span> </li>{% endfor %}
        </ul>
        {% endif %}
        </div>

    {% endwith %}
    </div>
{{x}}
{% endblock %}